name = "CcallMacros"
uuid = "708bcaac-1406-11e9-0ec1-63a89b0112ed"
authors = ["Aaron Christianson <ninjaaron@gmail.com>"]
version = "0.1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
